### ISSUE TITLE
How can I modify VerboseFlag 

### ISSUE THREAD

**Issue by papozhang** [apenella/go-ansible#113]
https://github.com/apenella/go-ansible/blob/ad0142112a3e81102b3676e43972ac234069c0a9/pkg/playbook/ansiblePlaybook.go#L84

I want to customize VerboseFlag = "-v"

**Comment by apenella** [comment]
Hi! @papozhang 
unfortunately, at this moment you can't customize that flag.
I would give it a thought for the future version but I will not implement a solution in short term.

Thanks for your understanding!

**Comment by apenella** [comment]
HI @papozhang 
I am going to merge PR #115 which will allow you to define multiple verbosity levels either on the ansible-playbook or ansible ad-hoc commands.
