### ISSUE TITLE
SSH StrictHostKeyChecking

### ISSUE THREAD

**Issue by PaPerM7** [apenella/go-ansible#127]
Hi 
I wanted to know if there is a way to set StrictHostKeyChecking=no when im running my ansible playbook.
I tried to add `SSHCommonArgs: "-o StrictHostKeyChecking=no"` to `ansiblePlaybookConnectionOptions` but it seems that its not working. i wanted to make sure if im doing it the right way or my attempts are just hopeless.
Thank you for responding <3

**Comment by apenella** [comment]
Hi! @PaPerM7 
Thanks for spotting that!
I have seen that those arguments were not quoted and it could be the cause of your issue.

I created the pull request #128  which should solve. Would you mind checking it before preparing a new release including the fix?

Thanks!

**Comment by apenella** [comment]
@PaPerM7 
Did you have the chance to validate the PR https://github.com/apenella/go-ansible/pull/128?

Thanks!

**Comment by apenella** [comment]
@PaPerM7 I added the fix on the release v1.2.1
