### ISSUE TITLE
[Question] Can we use alias for inventory?

### ISSUE THREAD

**Issue by jasonlaw** [apenella/go-ansible#129]
If yes, any example reference?

**Comment by apenella** [comment]
Hi @jasonlaw!
Thanks for your question.

If Ansible supports the alias, you can use them through go-ansible.

Behind the scenes, the library uses the ansible or ansible-playbook commands you have installed on your machine. therefore, any Ansible project you run through go-ansible should work as it was executed directly using the Ansible commands.

In case the aliases do not work, please provide me with some examples to reproduce the error and I will work on it.

Thanks!

**Comment by jasonlaw** [comment]
Hi @apenella,
Looks like the Ansible does not support for alias without the inventory file.
Anyway, I have tried different approach and it works work for my case. 
Thank you for this great package! :)

**Comment by apenella** [comment]
Hi @jasonlaw!
It is good to know that you already have found a way to solve your case :smile: 
If you need anything else feel free to let me know.
Thanks!
