### ISSUE TITLE
Suggestion for a Feature to Execute Inventory-Related Commands

### ISSUE THREAD

**Issue by chungeun-choi** [apenella/go-ansible#132]
Hello to all contributors of this project! I'm chungeun, working at a cloud company called Okestro. I wanted to express my gratitude as your project has been incredibly helpful to me!

I'm writing this issue to suggest an addition to the inventory functionality. Specifically, I'm interested in implementing a feature under ‘./lib/ansible/cli/inventory’ in the main Ansible project. I believe adding this feature would be greatly beneficial for our project currently in use. I'm curious to hear your thoughts on this!

* Ansible cli inventory
https://github.com/ansible/ansible/blob/4760dae989c8c86fe67cbcfbf2f11d8f51cda24a/lib/ansible/cli/inventory.py#L48-L102

Thank you for your hard work and dedication to this project.

**Comment by apenella** [comment]
Hi @chungeun-choi!
Thank you for your suggestion. At this moment I am working on go-ansible version 2. On that version, I want to include support for galaxy commands. Your suggestion sounds good. I will go ahead and evaluate it to include the inventory commands as well.

Thank you!

**Comment by apenella** [comment]
@chungeun-choi v1.3.0 is already available! Thank you so much!
