### ISSUE TITLE
Example for winrm connection configuration

### ISSUE THREAD

**Issue by pyriand3r** [apenella/go-ansible#136]
Is there any possibility to configure a winrm connection with the current feature set?

There are no options in the configuration so i was wondering if there is another possibility. Or would the support of winrm connections need to be implemented?

**Comment by apenella** [comment]
Hi @pyriand3r!
Thank you for opening that issue.
Regarding what you are asking for, it's important to note that the library is not an implementation of Ansible in Go. Instead, it is a wrapper over the Ansible installation on your system, allowing you to execute any `ansible` or `ansible-playbook` command on your host through go-ansible.

Does it solve your doubts?

Thanks!

**Comment by pyriand3r** [comment]
Hi @apenella,
thanks for the response.

I know that it is a wrapper, so i think a found a solution for my problem: env vars. Haven't tried it yet but it should be possible to configure ansible to connect via winrm through the env vars which i can set in go-ansible.

Closing this as it seems to be the answer.

Regards
