### ISSUE TITLE
cannot use go get v2

### ISSUE THREAD

**Issue by lingxiao26** [apenella/go-ansible#141]
go get github.com/apenella/go-ansible@v2.0.0-rc.1

outpupt: 
go: github.com/apenella/go-ansible@v2.0.0-rc.1: invalid version: module contains a go.mod file, so module path must match major version ("github.com/apenella/go-ansible/v2")

**Comment by apenella** [comment]
Hi @lingxiao26!
Thanks for pointing that out. I was not aware that Go forces you to rename the package name when you change to a major version v2 or higher. https://go.dev/wiki/Modules#semantic-import-versioning
I am already working on that in #142 to solve the issue. Meanwhile, you can use the v1.3.0. I hope to have everything ready in a couple of days.
