### ISSUE TITLE
Can I embed playbook and inventory file to binary after build

### ISSUE THREAD

**Issue by lingxiao26** [apenella/go-ansible#144]
[examples](https://github.com/apenella/go-ansible/tree/master/examples)/[ansibleplaybook-simple-embedfs](https://github.com/apenella/go-ansible/tree/master/examples/ansibleplaybook-simple-embedfs) have a example. But it just like move files to a temporary directory. It's not embed files to binary after build

**Comment by rhugga** [comment]
One suggestion. What I ended up doing is creating structs that you can yaml-marshal into viable ansible playbooks. It's not perfect and you might run into issues doing this with some of the more complex ansible modules. Then when I go to run a playbook, I serialize it into TMPDIR, run it from there, then remove the playbook. I no longer have playbooks embedded in the code or have long-living playbooks on disk.

For example, here is a playbook that uses ansible copy module:
```
type CopyPlaybook struct {
	Name           string           `yaml:"name"`
	Hosts          string           `yaml:"hosts"`
	GatherFacts    bool             `yaml:"gather_facts,omitempty"`
	Become         bool             `yaml:"become,omitempty"`
	IgnoreErrors   bool             `yaml:"ignore_errors,omitempty"`
	AnyErrorsFatal bool             `yaml:"any_errors_fatal,omitempty"`
	Tasks          []CopyModuleTask `yaml:"tasks"`
}

// CopyModuleTask encapsulates options for the ansible copy module
type CopyModuleTask struct {
	Name       string         `yaml:"name"`
	Register   string         `yaml:"register,omitempty"`
	FailedWhen []string       `yaml:"failed_when,omitempty"`
	DelegateTo string         `yaml:"delegate_to,omitempty"`
	Module     CopyModuleArgs `yaml:"ansible.builtin.copy"`
}

// CopyModuleArgs encapsulates ansible copy module args
type CopyModuleArgs struct {
	Src       string `yaml:"src,omitempty"`
	RemoteSrc string `yaml:"remote_src,omitempty"`
	Dest      string `yaml:"dest,omitempty"`
	Owner     string `yaml:"owner,omitempty"`
	Group     string `yaml:"group,omitempty"`
	Mode      string `yaml:"mode,omitempty"`
	Content   string `yaml:"content,omitempty"`
	Follow    string `yaml:"follow,omitempty"`
	Backup    string `yaml:"backup,omitempty"`
	Validate  string `yaml:"validate,omitempty"`
}
```

Im actually working on making this more generic so each module doesn't need dedicated structs.

**Comment by apenella** [comment]
Hi @lingxiao26!
Did you have the chance to validate the example again or reviewed the suggestion did by @rhugga?

**Comment by apenella** [comment]
I will close the issue due to inactivity. Feel free to open a new issue if you need further assistance!
Thank you!
