### ISSUE TITLE
extra vars not being set

### ISSUE THREAD

**Issue by gjansen42** [apenella/go-ansible#145]
It seems like my version of ansible wants single quotes around the extra vars on the command line, and your Execute does not provide them

Command executed:
/usr/local/bin/ansible-playbook --extra-vars {"ansible_port":"55522"} --inventory www.google.com, --connection ssh --private-key ~/.ssh/id_rsa --user root /tmp/1209276947/disc.yml

for example, it wants --extra-vars '{"fruit":"apple"}' and without the single quotes it fails to load the extra vars 

You can see in the first run of ansible-playbook below without the single quotes it uses the default port 22. In the second run with the single quotes it tries 55522

root@dev:/opt/satellite/bin# ansible --version
ansible [core 2.16.4]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

root@dev:/opt/satellite/bin# /usr/local/bin/ansible-playbook --extra-vars {"ansible_port":"55522"} --inventory www.google.com, --connection ssh --private-key ~/.ssh/id_rsa --user root site.yml

PLAY [all] ************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************
fatal: [www.google.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host www.google.com port 22: Network is unreachable", "unreachable": true}

PLAY RECAP ************************************************************************************************************************************************
www.google.com             : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

root@dev:/opt/satellite/bin# /usr/local/bin/ansible-playbook --extra-vars '{"ansible_port":"55522"}' --inventory www.google.com, --connection ssh --private-key ~/.ssh/id_rsa --user root site.yml

PLAY [all] ************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************
fatal: [www.google.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host www.google.com port 55522: Network is unreachable", "unreachable": true}

PLAY RECAP ************************************************************************************************************************************************
www.google.com             : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

**Comment by apenella** [comment]
Hi @gjansen42!
Thanks for opening that issue!

I have checked the extra-vars and seems that are being quoted.
I prepared the example [ansibleplaybook-extravars](https://github.com/apenella/go-ansible/blob/version-2.0.0-prerelease-2/examples/ansibleplaybook-extravars/ansibleplaybook-extravars.go) that you can execute to validate it. That is my output:

```
go run ansibleplaybook-extravars.go
Command:  ansible-playbook  --extra-vars '{"extravar1":"value11","extravar2":"value12"}' --inventory 127.0.0.1, --connection local --user apenella site.yml

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]

TASK [show values] *************************************************************
ok: [127.0.0.1] =>
  msg: |-
    value11
    value12

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Which version of go-ansible are you using? I executed the example using the v2.0.0-rc.2 but it should behave in the same way if you use v1.3.0.

I am using the same Ansible version as you:
```
$ ansible --version
ansible [core 2.16.4]
  config file = -/.ansible.cfg
  configured module search path = ['-/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /-/.local/lib/python3.10/site-packages/ansible
  ansible collection location = -/.ansible/collections:/usr/share/ansible/collections
  executable location = -/.local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

On the other hand, I have seen on your snippets that the output for quoted and unquoted extra-vars is the same. If that is the case, it makes me think that the cause should be another one.

```
fatal: [www.google.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host [www.google.com](http://www.google.com/) port 55522: Network is unreachable", "unreachable": true}
```

Can you reach your remote host?

**Comment by gjansen42** [comment]
Here is the version I am using, pulled from go.mod:

        github.com/apenella/go-ansible/v2 v2.0.0-rc.2
        github.com/apenella/go-common-utils/data v0.0.0-20220913191136-86daaa87e7df // indirect
        github.com/apenella/go-common-utils/error v0.0.0-20220913191136-86daaa87e7df // indirect

Thanks

-Greg
________________________________

**Comment by gjansen42** [comment]
A little more info. I am on an ARM machine. I know I have had issues with that in the past. Maybe I will try on an x86

***@***.***:/# uname -a
Linux explorer-dev 6.5.0-1018-oracle #18~22.04.1-Ubuntu SMP Sat Feb 17 22:00:50 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

-Greg
________________________________

**Comment by apenella** [comment]
Hi @gjansen42!
Thanks for the info.
Did you have the chance to execute the example [ansibleplaybook-extravars](https://github.com/apenella/go-ansible/blob/version-2.0.0-prerelease-2/examples/ansibleplaybook-extravars/ansibleplaybook-extravars.go)?

I'll try to reproduce your scenario, changing the `ansible_port` through an extra-var.

**Comment by apenella** [comment]
I already updated the [ansibleplaybook-extravars](https://github.com/apenella/go-ansible/blob/version-2.0.0-prerelease-2/examples/ansibleplaybook-extravars/ansibleplaybook-extravars.go) example and I could set the ansible_port as an extra-var

```
/code/examples/ansibleplaybook-extravars # go run ansibleplaybook-extravars.go
Command:  ansible-playbook  --extra-vars '{"ansible_port":"22225","extravar1":"value11","extravar2":"value12"}' --inventory inventory.yml --ssh-common-args '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' site.yml

PLAY [server] ******************************************************************

TASK [Gathering Facts] *********************************************************
[WARNING]: Platform linux on host server is using the discovered Python
interpreter at /usr/local/bin/python3.12, but future installation of another
Python interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.16/reference_appendices/interpreter_discovery.html for more information.
ok: [server]

TASK [show values] *************************************************************
ok: [server] => {
    "msg": "value11\nvalue12\n"
}

PLAY RECAP *********************************************************************
server                     : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Could it be that you get confused because the command in the error's output is not properly formatted and lacks quotes?

**Comment by apenella** [comment]
The fix is available in https://github.com/apenella/go-ansible/releases/tag/v2.0.0
