### ISSUE TITLE
Inquiry about Referencing Executed Processes in DefaultExecute Object

### ISSUE THREAD

**Issue by chungeun-choi** [apenella/go-ansible#150]
Hello,

I have a question regarding the DefaultExecute object. Is there a property that allows us to reference the process that has been executed? We are looking for a variable that can track the Ansible tasks executed to ensure they are properly monitored.

Thank you.

**Comment by apenella** [comment]
hi @chungeun-choi!
Thank you for your question. Unfortunately, at this moment, it is not possible to grab the ID of the spawned process. The [Cmd](https://github.com/apenella/go-ansible/blob/master/pkg/execute/defaultExecute.go#L200) is instantiated inside the [Execute](https://github.com/apenella/go-ansible/blob/master/pkg/execute/defaultExecute.go#L159) method of the [DefaultExecutor](https://github.com/apenella/go-ansible/blob/master/pkg/execute/defaultExecute.go#L64) and is not accessible from outside.

One solution that comes to mind is to create an Executor inspired by DefaultExecutor, where you can have more control over the `Cmd`.

I will consider if it is possible to achieve this while maintaining an agnostic [Executable](https://github.com/apenella/go-ansible/blob/master/pkg/execute/defaultExecute.go#L74) within the DefaultExecutor.

**Comment by chungeun-choi** [comment]
Hi @apenella ,
Thank you for your response. I will proceed with developing a custom Executor object.
