### ISSUE TITLE
can not parse playbook file, like site.yml

### ISSUE THREAD

**Issue by yjbdsky** [apenella/go-ansible#19]
this library can not parse playbook file, like site.yml?

**Comment by apenella** [comment]
@yjbdsky no the library just runs the playbook using your system's `ansible-playbook`.
Do you have any other question?

Regards,

**Comment by clementblaise** [comment]
Is it possible to pass an inventory file as `ansible-playbook -i <inventory>` option ?

**Comment by apenella** [comment]
@yjbdsky since there is no other question, I close this issue.
