### ISSUE TITLE
Add virtualenv option

### ISSUE THREAD

**Issue by clementblaise** [apenella/go-ansible#21]
Hello,

Right now it's only possible to launch with the default `ansible-playbook` binary. 

As you may know managing Ansible modules directly through default `pip` installed on the system is a nightmare (I have already broken machine myself ;). The best practice we have is to always set it up through virtualenv and I think it's pretty conventional.

I am aware that it would work when the virtualenv is already loaded, but it would be nice to provide a way to overwrite the default binary. Similar to how ansible provide the `ansible_python_interpreter` var

I can submit a PR

**Comment by apenella** [comment]
hi @clementblaise.
As I could understand, you propose to have the chance to configure the binary. 
I could work on it on the next few days, it should not be complicated.

In case you already code it, submit a PR.

**Comment by apenella** [comment]
hi @clementblaise 
I created #22 that includes what you proposed.

**Comment by clementblaise** [comment]
Thanks @apenella I did't have the time to work on the PR, looks perfect !
