### ISSUE TITLE
exec: "ansible-playbook": executable file not found in %PATH%

### ISSUE THREAD

**Issue by marksugar** [apenella/go-ansible#24]
windows vscode use 
```
panic: Binary file 'ansible-playbook' does not exists
        exec: "ansible-playbook": executable file not found in %PATH%

goroutine 1 [running]:
```
linux all normal

windows application how to set this individual PATH 。ansible-playbook file create ok

thanks

**Comment by apenella** [comment]
Hi! @marksugar 
I included the `exec.LookPath` validation on #22, since you could use any `ansible-playbook` binary on `AnsiblePlaybookCmd`.
Have you tried to define the whole `ansible-playbook` path on [`AnsiblePlaybookCmd.Binary`](https://github.com/apenella/go-ansible/blob/master/ansiblePlaybook.go#L108)? You could also include your `ansible-playbook`'s folder on the PATH. 

Have you been using `go-ansible` before [v0.7.0](https://github.com/apenella/go-ansible/releases/tag/v0.7.0)?

Regards,

**Comment by apenella** [comment]
Hi @marksugar 
there is any update about these issue?

**Comment by morningspace** [comment]
@apenella Just a quick question, I see the `DefaultAnsiblePlaybookBinary` in code, but I have no idea where the default one comes from. Is there a default binary available (and what version it is), or I should always specify a binary by myself using `AnsiblePlaybookCmd.Binary`?

**Comment by apenella** [comment]
hi @morningspace 
Thanks for your question.

[exec.LookPath](https://pkg.go.dev/os/exec#LookPath) is used to locate the binary path. You could see it [here](https://github.com/apenella/go-ansible/blob/master/pkg/playbook/ansiblePlaybook.go#L123).

I hope that it could help you.

regards!

**Comment by gy95** [comment]
I also encountered this problem, i run `github.com/apenella/go-ansible/examples/cobra-cmd-ansibleplaybook` example, and the error output is like below:
what can I do to build or download `ansible-playbook` binary? @apenella , thanks :)
```
~/go/src/github.com/apenella/go-ansible/examples/cobra-cmd-ansibleplaybook# go run cobra-cmd-ansibleplaybook.go -L -i 127.0.0.1, -p site.yml -e example="hello go-ansible!"
Error: Binary file 'ansible-playbook' does not exists
	exec: "ansible-playbook": executable file not found in $PATH
Usage:
  cobra-cmd-ansibleplaybook [flags]

Flags:
  -L, --connection-local    Run playbook using local connection
  -e, --extra-var strings   Set extra variables to use during the playbook execution. The format of each variable must be <key>=<value>
  -h, --help                help for cobra-cmd-ansibleplaybook
  -i, --inventory string    Specify ansible playbook inventory
  -p, --playbook strings    Playbook(s) to run

Binary file 'ansible-playbook' does not exists
	exec: "ansible-playbook": executable file not found in $PATH
exit status 1
```

**Comment by apenella** [comment]
Hi @gy95 
`go-ansible` requires ansible to be installed. 
I should include a requirements section on the README.md page.

**Comment by gy95** [comment]
> Hi @gy95 `go-ansible` requires ansible to be installed. I should include a requirements section on the README.md page.

yes, just run `apt install ansible`
