### ISSUE TITLE
How to connection other nodes?

### ISSUE THREAD

**Issue by XuHaoIgeneral** [apenella/go-ansible#3]
> ansiblePlaybookConnectionOptions := &ansibler.AnsiblePlaybookConnectionOptions{
                Connection: "local",
        }

when i chnage `Connection: local`  to  `Connection:<my node ip>`  。
> ansiblePlaybookConnectionOptions := &ansibler.AnsiblePlaybookConnectionOptions{
                Connection: "192.168.1.176",
        }

*Additional context:*
> Go-ansible example =>  fatal: [192.168.1.176]: FAILED! => {"msg": "the connection plugin '192.168.1.176' was not found"}
Go-ansible example =>  	to retry, use: --limit @/root/go/src/github.com/apenella/go-ansible/examples/simple-ansibleplaybook/site.retry
Go-ansible example =>  
Go-ansible example =>  PLAY RECAP

**Comment by apenella** [comment]
Hi, @XuHaoIgeneral 
In that case you would skip `Connection` definition. You should define your node on ansible's inventory and set the playbook hosts to use that node.

**Comment by XuHaoIgeneral** [comment]
> n. You should define your node on ansible's inventory and set the playbook hosts to use that node.

thanks.
