### ISSUE TITLE
feature: Cmd run Dir

### ISSUE THREAD

**Issue by zhangguanzhang** [apenella/go-ansible#31]
need ansible-plabook run `Dir` set
https://pkg.go.dev/os/exec#Cmd  `Cmd.Dir`

**Comment by apenella** [comment]
hi @zhangguanzhang 
would you describe a little bit more which is your proposal? Is that a missing `ansible-playbook` option... what do you expect about this feature? Could you give me some example?
Is not enough to define the playbook location on `AnsiblePlaybookCmd`?

Thank you very much!

**Comment by zhangguanzhang** [comment]
cmd.Path should could be set by user

**Comment by zhangguanzhang** [comment]
I really need this feature, can you complete it in a short time？

**Comment by zhangguanzhang** [comment]
Looking forward to the release of the next tab version

**Comment by apenella** [comment]
@zhangguanzhang I merged #31 so quick that I was not realized about your update on `Executor` interface, which includes the method `SetCmdRunDir`. That is a breaking change and to avoid you to wait till v1.0.0, I would like to rethink it in some way to keep the original interface definition. Keeping the original interface will let me to release ' v0.8.0' earlier, may be on the next couple of days. 
Do you need the method `SetCmdRunDir` on the interface for some reason?
Thanks!

**Comment by apenella** [comment]
Hi @zhangguanzhang 
v0.8.0 with CmdRunDir has been released with no breaking changes.

I am refining the last ideas for v1.0.0, which will come with a few breaking changes. One of these breaking changes is a way to define options for Executor.
