### ISSUE TITLE
feature: support interactive input from stdin

### ISSUE THREAD

**Issue by rfc2119** [apenella/go-ansible#43]
I have a playbook file which requires user input in order to progress. Currently, when invoking an interactive playbook from go-ansible default values for user input are taken.

How do you think this might be supported ? I was thinking of piping the stdin of `go-ansible` to ansible's stdin

**Comment by apenella** [comment]
Hi! @rfc2119 
Time ago I tried to write an example doing something similar to your propose but I never finished it :(
I take your idea and I am going to think how to fit it in `go-ansible`.

btw, I could remember that I used the library https://github.com/Netflix/go-expect.

**Comment by apenella** [comment]
@rfc2119 thank you very much for #48

**Comment by apenella** [comment]
feature available on v1.1.0
