### ISSUE TITLE
Ansible playbook with wrong IP hang up

### ISSUE THREAD

**Issue by dikkini** [apenella/go-ansible#45]
I launch ansible playbook using go-ansible with wrong IP address (real IP is 192.168.2.10, i specify 192.168.2.12 - no host with such IP address). It hangup for more than 600 seconds. Sometimes 1 hour timeout, before i get an error that host is unreachable. No specific settings in code, just run playbook with specific inventory. If i sepcify wrong ssh port (23 instead of 22) - i will get an error in 10-15 seconds.

If i run ansible playbook command directly - i'll get an error very fast.

**Comment by apenella** [comment]
hi! @dikkini 
I will try to reproduce it. 
Just to know a little bit more, have you defined a timout on  `AnsiblePlaybookConnectionOptions`? It still happens?

Thanks!

**Comment by dikkini** [comment]
Yes. I defined timeout in connect options.

**Comment by apenella** [comment]
hi @dikkin!i
I couldn't reproducte it yet.
which go-ansible version are you running?  
thanks!

**Comment by dikkini** [comment]
Latest. 0.8

**Comment by apenella** [comment]
Hi @dikkini,

I am trying to reproduce what you are describing using the `simple-ansibleplaybook` example as base, and I could not hang it.
I updated the code to run an ansible playbook placed on my host and I update the playbooks inventory to use an unreachable vm, 192.168.0.48.
```go
        ansiblePlaybookOptions := &ansibler.AnsiblePlaybookOptions{
		Inventory: "inventory/development/development.ini",
	}

	playbook := &ansibler.AnsiblePlaybookCmd{
		Playbook:          "site.yml",
		CmdRunDir:         "/projects/ansible/ansible-dev-playbook",
		Options:           ansiblePlaybookOptions,
		ExecPrefix:        "Go-ansible example",
	}
```
The playbook has the gathering facts enabled and it fails in a few seconds.
```
(master)$ time go run simple-ansibleplaybook.go
Go-ansible example ──
Go-ansible example ── PLAY [core] ********************************************************************
Go-ansible example ──
Go-ansible example ── TASK [Gathering Facts] *********************************************************
Go-ansible example ── fatal: [vm-dev]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.0.48\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.0.48 port 22: No route to host\r\n", "unreachable": true}
Go-ansible example ──
Go-ansible example ── PLAY RECAP *********************************************************************
Go-ansible example ── vm-dev           : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
Go-ansible example ──
Go-ansible example ── Playbook run took 0 days, 0 hours, 0 minutes, 3 seconds
panic: Error during command execution: ansible-playbook error: parser error

Command executed: ansible-playbook --inventory inventory/development/development.ini site.yml

exit status 4

goroutine 1 [running]:
main.main()
        go-ansible/examples/simple-ansibleplaybook/simple-ansibleplaybook.go:28 +0x129
exit status 2

real    0m4.101s
user    0m1.771s
sys     0m0.267s
```

Since I can not reproduce it I will need more details to work on it? I think that is not enough to run the playbook againts an unreachable host.
Does it fails at the verfy begining of the playbook run or fails on a specific task?

Thanks!

**Comment by dikkini** [comment]
It fails at start, I ll try to reproduce it tomorrow using your code

**Comment by apenella** [comment]
hi @dikkini 
are you still facing that issue?

thanks!

**Comment by apenella** [comment]
Since there is no response, I am going to close that issue. 
@dikkini In case you could reproduce it, just reopen it!

thanks!
