### ISSUE TITLE
ssh port change

### ISSUE THREAD

**Issue by linkingli** [apenella/go-ansible#47]
I have modified the port of Ansible SSH and now use Go-Ansible to run Ansible PlayBook. How can I run it properly。

**Comment by apenella** [comment]
hi! @linkingli 
have you tried to set the variable `ansible_port` either on your inventory or as an extra-var?

Thanks!

**Comment by linkingli** [comment]
Wow, thanks for replying to me so quickly, I was just about to give it a try, thanks

@apenella

**Comment by apenella** [comment]
hi @linkingli 
have you already solved it'

thanks!

**Comment by apenella** [comment]
Since there is no response, I am going to close that issue.
@linkingli in case you need anything else about that issue, just reopen it.

Thanks!
