### ISSUE TITLE
How to pass -u and --ask-become-pass options?

### ISSUE THREAD

**Issue by koddr** [apenella/go-ansible#5]
Hello! Thanks for this Go package.

Can you tell me please, how to pass `-u` and `--ask-become-pass` to execution via your package?

Thanks! 😉

**Comment by apenella** [comment]
Hi @koddr 
The package is not ready to use those arguments but I will include them on the next few days.

Thanks!

**Comment by koddr** [comment]
@apenella thx for reply!

Okay, I understand you. Can't wait to test this on my project 👍

**Comment by apenella** [comment]
@koddr [version 0.4.0](https://github.com/apenella/go-ansible/commit/d4c420ecbd5af288b016084c08f8c10d4487562b) includes escalation privileged options and new opt on connection options to set the ssh user.

**Comment by koddr** [comment]
@apenella thx! You rock 👍
