### ISSUE TITLE
If it is possible to add a list variable as extra-vars

### ISSUE THREAD

**Issue by xiangpingjiang** [apenella/go-ansible#55]
```
ansible-playbook arcade.yml --extra-vars '{"pacman":"mrs","ghosts":["inky","pinky","clyde","sue"]}'
```
in the example of go-ansible:
```
ansiblePlaybookOptions.AddExtraVar("app_name", app_name)
```
The value of the extra-vars must be string?
If it is possible to add a list variable as extra-vars?
Thank you very much

**Comment by apenella** [comment]
hi @xiangpingjiang 
As you could see on the link below `AddExtraVar` method accepts an interface{} as value, then it can be an slice, int, bool,.. or even another map.
https://github.com/apenella/go-ansible/blob/master/pkg/playbook/ansiblePlaybook.go#L414

Following your `ansble-playbook` command, you need to define the ghosts values on a slice and then pass it as value.
```
ghosts_values := []string{"inky","pinky","clyde","sue"}
playbook.AddExtraVar("ghosts", ghosts_values)
```
Do you have anyother question?

Thanks!

**Comment by xiangpingjiang** [comment]
Hi @apenella 
thanks for your reply
I have tried  it, but i got a panic: Unmarshall error
json: cannot unmarshal array into Go struct field AnsiblePlaybookJSONResultsPlayTaskHostsItem.plays.tasks.hosts.msg of type string

**Comment by weichenqi** [comment]
Hi @apenella 
When I excute with command----(1.1.1.1 is unrechabled host for test)
/opt/homebrew/bin/ansible-playbook --extra-vars '{"host_name":"10.200.75.152,10.200.75.136,1.1.1.1"}' --inventory 10.200.75.136,10.200.75.152,1.1.1.1 --user root nstall-nginx.yml 
is ok.
but with go-ansible i got a panic:
panic: Error during command execution: ansible-playbook error: parser error
tips:when i del 1.1.1.1, it just ok with go-ansible

code:

func ansiblePlaybookTask(_, f, inventory string, jsonvars map[string]interface{}){
	ansiblePlaybookConnectionOptions := &options.AnsibleConnectionOptions{
		//Connection: "local",
		User:       "root",
	}

	ansiblePlaybookOptions := &playbook.AnsiblePlaybookOptions{
		Inventory: 					inventory,
		//Inventory: "/root/inventory",
		ExtraVars:              jsonvars,
	}

	playbook := &playbook.AnsiblePlaybookCmd{
		Playbooks:         []string{f},
		ConnectionOptions: ansiblePlaybookConnectionOptions,
		Options:           ansiblePlaybookOptions,
		StdoutCallback:    "json",
	}

	err := playbook.Run(context.TODO())
	if err != nil {
		panic(err)
	}
}

thanks!
