### ISSUE TITLE
Typos in README.md

### ISSUE THREAD

**Issue by rvben** [apenella/go-ansible#57]
There are a number of typos in the README file.
lastest > latest
recieves > receives
ansbile > ansible

**Comment by apenella** [comment]
Hi @rvben 
Thank you very much!
I have seen that you have also reviewed some language mistakes. Would you mind creating a PR?

**Comment by rvben** [comment]
Hi @apenella

Thanks for your response. You can find the PR at https://github.com/apenella/go-ansible/pull/58.
Let me know if it's good like this.

**Comment by apenella** [comment]
Thanks a lot @rvben 
I just merged it!
