### ISSUE TITLE
How to get success result?

### ISSUE THREAD

**Issue by wahello** [apenella/go-ansible#59]
### How to get success result?

**Comment by apenella** [comment]
HI @wahello 
could you extend you question or give some more context, please?
Folder `https://github.com/apenella/go-ansible/tree/master/examples` has several examples where you could see how to manage Ansible results.

Thanks!

**Comment by wahello** [comment]
@apenella Like executing builtin module `setup`, if successful, how to obtain the hardware info of the results in code? The result is printed in log.

**Comment by apenella** [comment]
Hi @wahello!
`go-ansible` executes `ansible` commands. To achieve `setup`'s module results you need to update ansible playbook to do that. You could do it using ansible's `debug` module.

Let me know if you have any update!
Thanks

**Comment by wahello** [comment]
@apenella I must missed something. How to get the print log, excuting this line
```err := adhoc.Run(context.TODO())```
when err is nil?.

**Comment by wahello** [comment]
I got it.

**Comment by cyberchao** [comment]
> @apenella I must missed something. How to get the print log, excuting this line
> `err := adhoc.Run(context.TODO())` [in examples](https://github.com/apenella/go-ansible/blob/master/examples/simple-ansibleadhoc/simple-ansibleadhoc.go)
> when err is nil?.

hi, Have you found a solution？i need to get adhoc result also.

**Comment by apenella** [comment]
Hi! @cyberchao 
by default, when you run an ad hoc command, its output is printed to stdout.

In case you would manage the output, such as is done when you use `json` stdout callback, you need to create your own executor and store the command output to a buffer.
Take a look at that example:
https://github.com/apenella/go-ansible/blob/master/examples/json-stdout-ansibleplaybook/json-stdout-ansibleplaybook.go#L31

I hope it could help you! Let me know if you need anything else.

**Comment by wahello** [comment]
@apenella Exactly!

> Hi! @cyberchao
> by default, when you run an ad hoc command, its output is printed to stdout.
> 
> In case you would manage the output, such as is done when you use `json` stdout callback, you need to create your own executor and store the command output to a buffer.
> Take a look at that example:
> https://github.com/apenella/go-ansible/blob/master/examples/json-stdout-ansibleplaybook/json-stdout-ansibleplaybook.go#L31
> 
> I hope it could help you! Let me know if you need anything else.
