### ISSUE TITLE
how to get error during command execution？

### ISSUE THREAD

**Issue by aohan0503** [apenella/go-ansible#63]

**Comment by aohan0503** [comment]
like this
![image](https://user-images.githubusercontent.com/81146139/125583190-493d30ad-7c96-4581-bdf3-ce3de482750f.png)

**Comment by apenella** [comment]
Hi @aohan0503 
When you use `DefaultExecutor` already shows the errors

I forced an  ansible parser error on `signals-and-cancellation-ansibleplaybook` example and that is the result:
```go
go-ansible/examples/signals-and-cancellation-ansibleplaybook❯ go run signals-and-cancellation-ansibleplaybook.go
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected '-' indicator

The error appears to be in '/home/aleix/projects/aleix.penella/go-ansible/examples/signals-and-cancellation-ansibleplaybook/site.yml': line 7, column 6, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - name: signals-and-cancellation-ansibleplaybook
     debug:
     ^ here
Error during command execution: ansible-playbook error: parser error

Command executed: /home/aleix/.local/bin/ansible-playbook --inventory 127.0.0.1, --connection local --user aleix site.yml
```

Share some code snippets If you need more help.

Thanks!

**Comment by apenella** [comment]
hi @aohan0503!
There is any update about your issue?

Thanks!

**Comment by aohan0503** [comment]
hi @apenella 
I want to get the stderr when ansible is executed ,errors like parsing errors。
Get stderr through go-ansible

**Comment by aohan0503** [comment]
Use execute.WithWriteError() method to get

Thanks!

**Comment by apenella** [comment]
Hi @aohan0503!
I understand that you figured out how to solve it. Do you need anything else? Would you mind If I am closing that issue?

**Comment by aohan0503** [comment]
@apenella This issue can now be clos
