### ISSUE TITLE
help with remote options

### ISSUE THREAD

**Issue by LoveXayah** [apenella/go-ansible#70]
how can i connect to remote host to run ansible-playbook,the options in the code are local,can somebody share a remote config?

**Comment by apenella** [comment]
hi @LoveXayah 
thanks for your question.

The connection parameter is used to specify which connection plugin is going to be used to connect to the hosts.
In case that you want to connect to remote host, you need to define it on the ansible inventory and do not specify any connection, by default, ansible uses smart connection.

You could read more about connection to hosts on ansible [here](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#connecting-to-hosts-behavioral-inventory-parameters)

Thanks!
