### ISSUE TITLE
What's the difference between AnsibleAdhocCmd and AnsiblePlaybookCmd? 😄 

### ISSUE THREAD

**Issue by gy95** [apenella/go-ansible#83]
I find that this project provides two Packages: adhoc and playhook? what's the difference between the two packages? 
Can I use playhook package to do something that adhoc package intends to do? 😄 @apenella  Thanks a lot :)

**Comment by apenella** [comment]
hi! @gy95 
[AnsibleAdhocCmd](https://github.com/apenella/go-ansible/blob/master/pkg/adhoc/adhoc.go#L88) executes ansible ad hoc commands. Take a look at [this](https://docs.ansible.com/ansible/latest/user_guide/intro_adhoc.html). 
[AnsiblePlaybookCmd](https://github.com/apenella/go-ansible/blob/master/pkg/adhoc/adhoc.go#L88) execute ansible playbooks, [here](https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html#intro-to-playbooks) you could find the ansible documentation. 

I hope that it could help you!

**Comment by gy95** [comment]
Thanks 😄
