### ISSUE TITLE
AnsibleAdhocCmd return error when args has spaces

### ISSUE THREAD

**Issue by ylxxwx** [apenella/go-ansible#90]
When I use AnsibleAdhocCmd w/ Args('ping x.x.x.x -c 10'), I see this error. This command works in shell. The root cause is there are spaces in teh args. Any solution?

*errors.Error(&errors.Error{context:"(DefaultExecute::Execute)", message:"Error during command execution: ansible-playbook error: one or more host failed\n\nCommand executed:  /usr/bin/ansible all --args 'ping x.x.x.x -c 10' --inventory x.x.x.x, --module-name command --private-key ~/.ssh/gpc_rack_id_rsa\n\nexit status 2", wrappedErrors:[]error(nil)})

**Comment by apenella** [comment]
hi! @ylxxwx 
Thanks for rising that issue.
Let me check it.

btw, does it also fails if you execute the command that is show on the error message?

**Comment by apenella** [comment]
hi @ylxxwx 
Can you take a look at [command-module-ansibleadhoc](https://github.com/apenella/go-ansible/blob/fix/adhoc-args-with-space/examples/command-module-ansibleadhoc/command-module-ansibleadhoc.go) example?

I made it run on my system:
```
❯ go run command-module-ansibleadhoc.go 
Command:  ansible all  --args 'ping 127.0.0.1 -c 2' --inventory  127.0.0.1, --module-name command  --connection local
127.0.0.1 | CHANGED | rc=0 | (stdout) PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.\n64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.026 ms\n64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.048 ms\n\n--- 127.0.0.1 ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss, time 1001ms\nrtt min/avg/max/mdev = 0.026/0.037/0.048/0.011 ms
```

It also worked out on a remote server, using ssh connection:
```
❯ go run command-module-ansibleadhoc.go 
Command:  ansible all  --args 'ping 127.0.0.1 -c 2' --inventory  <IP>, --module-name command 
<IP> | CHANGED | rc=0 | (stdout) PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.\n64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.017 ms\n64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.021 ms\n\n--- 127.0.0.1 ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss, time 999ms\nrtt min/avg/max/mdev = 0.017/0.019/0.021/0.002 ms
```

As I could see on #91 , I did not change anything that should solves it, I just quoted the `Args` value on `AnsibleAdhocCmd`'s `String` method, which is a cosmetic update.

Let me know, if it helps you.

**Comment by ylxxwx** [comment]
Let me test it again. Will reply later.
