### ISSUE TITLE
you must install the sshpass program

### ISSUE THREAD

**Issue by torans** [apenella/go-ansible#95]
os:MacOS
go-ansible version:1.1.5
when that i set the "ansible_ssh_passwd" to the hosts file, i got the error:

"msg": "to use the 'ssh' connection type with passwords or pkcs11_provider, you must install the sshpass program"

i have installed the sshpass on my macos, how to solve the trouble?

**Comment by apenella** [comment]
Hi @torans 
Do you face the same error when you execute the playbook using `ansible-playbook` directly?

Does sshpass works when you execute it through command line (`sshpass -p mypass ssh myusername@myhost`)?

I will also try to reproduce it

**Comment by torans** [comment]
> @torans since there is no update on that issue, I am going to close it

Thanks. now it is normal for me.
